version: "3"

vars:
  bin_dir: "{{.HOME}}/bin"
  bin_name: "flow"
  alias_name: "fa"
  flow_native_path: "target/native/release/build/cli/flow/flow.exe"

tasks:
  flow:
    desc: Run the MoonBit flow CLI (passes CLI args through).
    silent: true
    cmds:
      - |
        set -euo pipefail
        moon run cli/flow -- {{.CLI_ARGS}}

  default:
    desc: List available tasks.
    silent: true
    cmds:
      - |
        task --list

  dev:
    desc: Alias for `task flow`.
    silent: true
    cmds:
      - |
        set -euo pipefail
        task flow -- {{.CLI_ARGS}}

  deploy:
    desc: Build the MoonBit flow CLI and install it to ~/bin/flow (with optional fa alias).
    silent: true
    cmds:
      - |
        set -euo pipefail
        moon run cli/flow --build-only --target native --release
        mkdir -p "{{.bin_dir}}"
        cp "{{.flow_native_path}}" "{{.bin_dir}}/{{.bin_name}}"
        chmod +x "{{.bin_dir}}/{{.bin_name}}"
        if [ -n "{{.alias_name}}" ]; then
          ln -sf "{{.bin_dir}}/{{.bin_name}}" "{{.bin_dir}}/{{.alias_name}}"
        fi
        case ":${PATH}:" in
          *:"{{.bin_dir}}":*) ;;
          *)
            echo "Note: {{.bin_dir}} is not currently on PATH."
            echo "Add it for fish with: fish_add_path $HOME/bin"
            echo "Or for bash/zsh: export PATH=\"$HOME/bin:$PATH\""
            ;;
        esac
  setup:
    desc: Ensure MoonBit CLI is installed and fetch project dependencies.
    silent: true
    cmds:
      - |
        set -euo pipefail
        if ! command -v moon >/dev/null 2>&1; then
          echo "MoonBit CLI 'moon' not found in PATH."
          echo "Install it with: curl -fsSL https://cli.moonbitlang.com/install/unix.sh | bash"
          echo "See install docs: https://www.moonbitlang.com/download/"
          exit 1
        fi
        # keep commands quiet but still fail fast on non-zero exit codes
        moon version >/dev/null
        moon install >/dev/null
        echo "✔️ you are setup"
